using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using STVrogue.GameLogic;
using STVrogue.Utils;
using static STVrogue.Utils.HelperPredicates;

namespace NUnitTests
{
    [TestFixture]
    
    // An example of a test that is is mostly generated by CoPilot. It helps,
    // but you have to put critical eyes on the suggestions. It is also not
    // perfect so you have to fix some things manually.
    // Still, it can be help in producing starting code.
    public class Test_Dungeon
    {
        // This a parameterized test for the constructor of the Dungeon class, in particular for
        // the linear shaped dungeon. The test is parameterized over the number of rooms N and
        // the maximum capacity of the rooms.
        [TestCase(-1,3)]
        [TestCase(5,-1)]
       [TestCase(2,3)]
       [TestCase(3,0)]
       [TestCase(3,1)]
       [TestCase(3,2)]
       [TestCase(3,3)]
       [TestCase(3,100)]
       [TestCase(100,5)]
       public void test_LinearDungeon(int N, int capacity)
        {
            // we cannot have a linear dungeon with less than 3 rooms
            if (N < 3)
            {
                Assert.Throws<ArgumentException>(() =>
                    new Dungeon(new RandomGenerator(123), DungeonShapeType.LINEAR, N, capacity));
                return;
            }
            // we cannot have a dungeon with less than 1 maximum capacity
            if (capacity < 1)
            {
                Assert.Throws<ArgumentException>(() =>
                    new Dungeon(new RandomGenerator(123), DungeonShapeType.LINEAR, N, capacity));
                return;
            }
            
            Dungeon dungeon = new Dungeon(new RandomGenerator(123), DungeonShapeType.LINEAR,N,capacity);
            // we have N rooms:
            Assert.IsTrue(dungeon.Rooms.Count == N);
            // each room has a unique ID:
            Assert.IsTrue(Forall(dungeon.Rooms, r => dungeon.Rooms.Count(r2 => r2.Id == r.Id) == 1));
            // each room has a capacity between 0 and capacity:
            Assert.That(Forall(dungeon.Rooms, r => r.Capacity >= 0 && r.Capacity <= capacity));
            // there is a unique startroom:
            Assert.IsTrue(dungeon.StartRoom != null);
            Assert.IsTrue(dungeon.Rooms.Count(r => r == dungeon.StartRoom) == 1);
            // there is a unique exitroom:
            Assert.IsTrue(dungeon.ExitRoom != null);
            Assert.IsTrue(dungeon.Rooms.Count(r => r == dungeon.ExitRoom) == 1);
            // all rooms are reachable from the startroom:
            Assert.IsTrue(Forall(dungeon.Rooms, r => dungeon.StartRoom.ReachableRooms().Contains(r)));
            // start and exit rooms have capacity 0:
            Assert.IsTrue(dungeon.StartRoom.Capacity == 0);
            Assert.IsTrue(dungeon.ExitRoom.Capacity == 0);
            // rooms neighbouring the exit room have maximum capacity:
            Assert.IsTrue(Forall(dungeon.ExitRoom.Neighbors, x => x.Item1.Capacity == capacity));
            // each room has at most 2 neighbours:
            Assert.IsTrue(Forall(dungeon.Rooms, r => r.Neighbors.Count <= 2));
            // the dungeon is linear, meaning there are no corners:
            Assert.IsTrue(Forall(dungeon.Rooms, r => r == dungeon.StartRoom ||
                                                     r == dungeon.ExitRoom ||
                                                     r.Neighbors[0].Item2 == Opposite(r.Neighbors[1].Item2)));
        }

       // generate some parameteried tests for the treedungeon please
       [TestCase(-1,3)]
       [TestCase(5,-1)]
       [TestCase(4,3)]
       [TestCase(5,3)]
       [TestCase(6,0)]
       [TestCase(6,1)]
       [TestCase(6,2)]
       [TestCase(6,3)]
       [TestCase(6,100)]
       [TestCase(100,5)]
        public void test_TreeDungeon(int N, int capacity)
        {
            // we cannot have a tree dungeon with less than 5 rooms
            if (N < 5)
            {
                Assert.Throws<ArgumentException>(() =>
                    new Dungeon(new RandomGenerator(123), DungeonShapeType.TREE, N, capacity));
                return;
            }
            // we cannot have a dungeon with less than 1 maximum capacity
            if (capacity < 1)
            {
                Assert.Throws<ArgumentException>(() =>
                    new Dungeon(new RandomGenerator(123), DungeonShapeType.TREE, N, capacity));
                return;
            }
            
            Dungeon dungeon = new Dungeon(new RandomGenerator(123), DungeonShapeType.TREE,N,capacity);
            // we have N rooms:
            Assert.IsTrue(dungeon.Rooms.Count == N);
            // each room has a unique ID:
            Assert.IsTrue(Forall(dungeon.Rooms, r => dungeon.Rooms.Count(r2 => r2.Id == r.Id) == 1));
            // each room has a capacity between 0 and capacity:
            Assert.That(Forall(dungeon.Rooms, r => r.Capacity >= 0 && r.Capacity <= capacity));
            // there is a unique startroom:
            Assert.IsTrue(dungeon.StartRoom != null);
            Assert.IsTrue(dungeon.Rooms.Count(r => r == dungeon.StartRoom) == 1);
            // there is a unique exitroom:
            Assert.IsTrue(dungeon.ExitRoom != null);
            Assert.IsTrue(dungeon.Rooms.Count(r => r == dungeon.ExitRoom) == 1);
            // all rooms are reachable from the startroom:
            Assert.IsTrue(Forall(dungeon.Rooms, r => dungeon.StartRoom.ReachableRooms().Contains(r)));
            // start and exit rooms have capacity 0:
            Assert.IsTrue(dungeon.StartRoom.Capacity == 0);
            Assert.IsTrue(dungeon.ExitRoom.Capacity == 0);
            // rooms neighbouring the exit room have maximum capacity:
            Assert.IsTrue(Forall(dungeon.ExitRoom.Neighbors, x => x.Item1.Capacity == capacity));
            // dungeon may not contain a cycle, use DFS to check for cycles:
            Assert.IsFalse(ContainsCycle(dungeon.StartRoom, null, new HashSet<Room>()));
            // the dungeon is not linear, meaning there is a corner somewhere:
            Assert.IsTrue(dungeon.Rooms.Any(r => r.Neighbors.Count > 2 || r.Neighbors[0].Item2 != Opposite(r.Neighbors[1].Item2)));
            // exit room may only have 1 neighbour
            Assert.IsTrue(dungeon.ExitRoom.Neighbors.Count == 1);
        }
        
        [TestCase(-1,3)]
        [TestCase(5,-1)]
        [TestCase(3,3)]
        [TestCase(4,3)]
        [TestCase(5,0)]
        [TestCase(5,1)]
        [TestCase(5,2)]
        [TestCase(5,3)]
        [TestCase(5,100)]
        [TestCase(6,3)]
        [TestCase(9,3)]
        [TestCase(100,5)]
         public void test_GridDungeon(int N, int capacity)
        {
            // we cannot have a tree dungeon with less than 4 rooms
            if (N < 4)
            {
                Assert.Throws<ArgumentException>(() =>
                    new Dungeon(new RandomGenerator(123), DungeonShapeType.GRID, N, capacity));
                return;
            }
            // we cannot have a dungeon with less than 1 maximum capacity
            if (capacity < 1)
            {
                Assert.Throws<ArgumentException>(() =>
                    new Dungeon(new RandomGenerator(123), DungeonShapeType.GRID, N, capacity));
                return;
            }
            
            Dungeon dungeon = new Dungeon(new RandomGenerator(123), DungeonShapeType.GRID,N,capacity);
            // we have N rooms:
            Assert.IsTrue(dungeon.Rooms.Count == N);
            // each room has a unique ID:
            Assert.IsTrue(Forall(dungeon.Rooms, r => dungeon.Rooms.Count(r2 => r2.Id == r.Id) == 1));
            // each room has a capacity between 0 and capacity:
            Assert.That(Forall(dungeon.Rooms, r => r.Capacity >= 0 && r.Capacity <= capacity));
            // there is a unique startroom:
            Assert.IsTrue(dungeon.StartRoom != null);
            Assert.IsTrue(dungeon.Rooms.Count(r => r == dungeon.StartRoom) == 1);
            // there is a unique exitroom:
            Assert.IsTrue(dungeon.ExitRoom != null);
            Assert.IsTrue(dungeon.Rooms.Count(r => r == dungeon.ExitRoom) == 1);
            // all rooms are reachable from the startroom:
            Assert.IsTrue(Forall(dungeon.Rooms, r => dungeon.StartRoom.ReachableRooms().Contains(r)));
            // start and exit rooms have capacity 0:
            Assert.IsTrue(dungeon.StartRoom.Capacity == 0);
            Assert.IsTrue(dungeon.ExitRoom.Capacity == 0);
            // rooms neighbouring the exit room have maximum capacity:
            Assert.IsTrue(Forall(dungeon.ExitRoom.Neighbors, x => x.Item1.Capacity == capacity));
        }
        
        Direction Opposite(Direction dir)
        {
            switch (dir)
            {
                case Direction.EAST:
                    return Direction.WEST;
                case Direction.WEST:
                    return Direction.EAST;
                case Direction.NORTH:
                    return Direction.SOUTH;
                case Direction.SOUTH:
                    return Direction.NORTH;
            }
            throw new Exception("Invalid direction");
        }
        
        // DFS to check for cycles in the dungeon
        bool ContainsCycle(Room current, Room? parent, HashSet<Room> visited)
        {
            visited.Add(current);
            foreach ((Room neighbor, _) in current.Neighbors)
            {
                if (neighbor == parent) continue;
                if (visited.Contains(neighbor) || ContainsCycle(neighbor, current, visited))
                    return true;
            }
            return false;
        }
    }
}